/* IPO Terminal IPO DNA v3: richer comparative decision view. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function validGmp(i){var gp=n(i.gmp_pct),g=n(i.gmp);return gp!=null&&gp>=-50&&gp<=100&&g!=null&&g>=-100&&g<=1000;}
function lot(i,m){var p=n(i.price),l=n(i.lot);return p!=null&&l!=null?p*l*m:null;}
function metric(i){
 var g=n(i.growth),roe=n(i.roe),roce=n(i.roce),de=n(i.de),pe=n(i.pe),fresh=n(i.fresh),ofs=n(i.ofs),prom=n(i.prom),sub=n(i.sub),gp=validGmp(i)?n(i.gmp_pct):null;
 var score=0,max=0,why=[],risk=[],evidence=0;
 if(g!=null){max+=16;evidence++;score+=g>=25?16:g>=20?14:g>=12?10:g>=5?6:0;if(g>=12)why.push('growth');else if(g<5)risk.push('weak growth');}
 if(roe!=null||roce!=null){max+=16;evidence++;var r=(roe!=null&&roce!=null)?(roe+roce)/2:(roe!=null?roe:roce);score+=r>=20?16:r>=15?13:r>=10?9:r>=5?5:0;if(r>=15)why.push('strong returns');else if(r<10)risk.push('weak returns');}
 if(pe!=null&&pe>0&&pe<100){max+=16;evidence++;score+=pe<=15?16:pe<=20?14:pe<=25?11:pe<=35?7:pe<=50?3:0;if(pe<=20)why.push('reasonable valuation');else if(pe>35)risk.push('high P/E');}
 if(de!=null&&de>=0){max+=14;evidence++;score+=de<=.2?14:de<=.4?12:de<=.6?9:de<=1?5:0;if(de<=.4)why.push('low debt');else if(de>1)risk.push('high debt');}
 if(fresh!=null||ofs!=null){max+=10;evidence++;var f=fresh!=null?fresh:(100-(ofs||0));score+=f>=70?10:f>=50?8:f>=30?5:2;if(f>=70)why.push('fresh capital');if(ofs!=null&&ofs>50)risk.push('high OFS');}
 if(prom!=null){max+=8;evidence++;score+=prom>=60?8:prom>=50?7:prom>=30?5:2;if(prom>=50)why.push('promoter alignment');}
 if(sub!=null){max+=10;evidence++;score+=sub>=50?10:sub>=20?9:sub>=10?8:sub>=3?5:sub>=1?3:0;if(sub>=10)why.push('strong demand');else if(sub<1)risk.push('weak/early demand');}
 if(gp!=null){max+=5;evidence++;score+=gp>=20?5:gp>=10?4:gp>=5?3:gp>=0?1:0;if(gp>=10)why.push('positive GMP sentiment');if(gp<0)risk.push('negative GMP sentiment');}
 var pct=max?Math.round(score/max*100):50;
 var coverage=['price','size','lot','open','close','sub','gmp','fresh','ofs','pe','roe','roce','rev','pat','ebitda','de','growth','prom'].filter(function(k){return ok(i[k]);}).length;
 var confidence=Math.min(100,35+coverage*3+evidence*2);
 if(!ok(i.pe))risk.push('valuation evidence missing');if(!ok(i.roe)&&!ok(i.roce))risk.push('return evidence missing');if(!ok(i.sub))risk.push('subscription evidence missing');
 return {score:pct,confidence:confidence,why:why.slice(0,4),risk:risk.slice(0,3),coverage:coverage,evidence:evidence,gmpValid:gp!=null};
}
function label(s){return s>=80?'Strong DNA':s>=70?'Healthy DNA':s>=60?'Mixed DNA':s>=50?'Caution DNA':'Weak DNA';}
function pill(k,v){return '<div class="dna-pill"><small>'+k+'</small><b>'+e(v)+'</b></div>';}
function render(){
 var p=document.getElementById('ipo-dna-panel');if(!p||!Array.isArray(window.ALL_IPOS))return;
 var list=window.ALL_IPOS.filter(function(i){return i&&i.name;}).map(function(i){return {i:i,s:metric(i)};}).sort(function(a,b){return b.s.score-a.s.score||b.s.confidence-a.s.confidence;});
 var h='<div class="panel-title">IPO DNA <button class="close-x" id="dna-close">Close</button></div>';
 h+='<div class="dna-intro"><div class="dna-hero"><span class="dna-icon">DNA</span><div><b>Which IPO has the stronger overall structure?</b><div class="tx3">DNA combines business growth, profitability, valuation, balance sheet, issue structure, promoter alignment, demand and sentiment into one comparable research view.</div></div></div><div class="dna-rule"><b>How to read it:</b> score = strength of available evidence · confidence = how much evidence is actually available · missing data reduces confidence, not automatically the score · GMP is secondary and corrupted/outlier GMP is ignored.</div></div>';
 h+='<div class="dna-summary"><b>Comparative DNA ranking</b><span class="tx3"> '+list.length+' IPOs · strongest evidence first</span></div><div class="dna-grid">';
 list.forEach(function(x,idx){var i=x.i,s=x.s,cl=s.score>=75?'gn':s.score>=60?'yl':'rd',gmp=s.gmpValid?(ok(i.gmp_pct)?i.gmp_pct:'positive'): 'Not used';
  h+='<div class="dna-card '+cl+'-dna"><div class="dna-head"><div><span class="dna-rank">#'+(idx+1)+'</span> <b>'+e(i.name)+'</b><div class="tx3">'+e(i.type||'IPO')+' · '+e(i.sector||'Sector unavailable')+' · '+e(i.status||'status TBA')+'</div></div><div class="dna-score"><b>'+s.score+'</b><span>/100</span></div></div>';
  h+='<div class="dna-label">'+label(s.score)+' <span>· '+s.confidence+'% confidence</span></div><div class="dna-pills">'+pill('GROWTH',ok(i.growth)?i.growth:'—')+pill('P/E',ok(i.pe)?i.pe:'—')+pill('ROE / ROCE',(ok(i.roe)?i.roe:'—')+' / '+(ok(i.roce)?i.roce:'—'))+pill('D/E',ok(i.de)?i.de:'—')+pill('FRESH / OFS',(ok(i.fresh)?i.fresh:'—')+' / '+(ok(i.ofs)?i.ofs:'—'))+pill('PROMOTER',ok(i.prom)?i.prom:'—')+pill('SUBSCRIPTION',ok(i.sub)?i.sub:'—')+pill('GMP',gmp)+'</div>';
  h+='<div class="dna-reasons"><div><small>POSITIVE EVIDENCE</small><b>'+e(s.why.length?s.why.join(' · '):'No strong positive signal yet')+'</b></div><div><small>CHECK NEXT</small><b>'+e(s.risk.length?s.risk.join(' · '):'No major warning in available evidence')+'</b></div></div>';
  h+='<div class="dna-lotbar"><span>1 Lot <b>'+(lot(i,1)!=null?'₹'+Math.round(lot(i,1)).toLocaleString('en-IN'):'TBA')+'</b></span><span>2 Lots <b>'+(lot(i,2)!=null?'₹'+Math.round(lot(i,2)).toLocaleString('en-IN'):'TBA')+'</b></span></div><div class="tx3" style="font-size:8px;margin-top:6px">Evidence: '+s.coverage+' fields · '+s.evidence+' scored factors · GMP: '+e(s.gmpValid?'valid secondary input':'ignored/unavailable')+'</div></div>';
 });
 h+='</div><div class="dna-footer">Transcript mode: ready. When your transcript is added, its exact selection principles will become the higher-priority rules for the DNA engine.</div>';p.innerHTML=h;p.classList.add('show');var b=document.getElementById('dna-btn');if(b)b.classList.add('active');var c=document.getElementById('dna-close');if(c)c.onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};
}
function init(){if(document.getElementById('dna-btn'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='dna-btn';b.textContent='IPO DNA';b.onclick=function(){var p=document.getElementById('ipo-dna-panel');if(p&&p.classList.contains('show')){p.classList.remove('show');b.classList.remove('active');}else render();};box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-dna-panel';document.body.appendChild(p);var st=document.createElement('style');st.textContent='.dna-intro{padding:10px;border-bottom:1px solid var(--bd)}.dna-hero{display:flex;gap:9px;align-items:center;font-size:12px}.dna-icon{display:flex;align-items:center;justify-content:center;width:42px;height:42px;border-radius:12px;background:linear-gradient(135deg,var(--gn),var(--bl));color:#fff;font-size:10px;font-weight:900}.dna-rule{margin-top:9px;padding:8px;border-radius:9px;background:linear-gradient(90deg,rgba(34,197,94,.10),rgba(59,130,246,.10),rgba(168,85,247,.10));font-size:9px}.dna-summary{padding:9px 10px;border-bottom:1px solid var(--bd)}.dna-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:9px;padding:9px}.dna-card{background:var(--card2);border:1px solid var(--bd);border-radius:12px;padding:10px;box-shadow:0 2px 12px rgba(0,0,0,.12)}.dna-card.gn-dna{border-left:4px solid var(--gn)}.dna-card.yl-dna{border-left:4px solid var(--yl)}.dna-card.rd-dna{border-left:4px solid var(--rd)}.dna-head{display:flex;justify-content:space-between;gap:8px}.dna-rank{color:var(--tx3);font-size:10px}.dna-score b{font-size:25px}.dna-score span{font-size:9px;color:var(--tx3)}.dna-label{margin:5px 0;font-size:10px}.dna-label span{color:var(--tx3)}.dna-pills{display:grid;grid-template-columns:1fr 1fr;gap:5px}.dna-pill{padding:6px;border:1px solid var(--bd);border-radius:7px;background:var(--card)}.dna-pill small,.dna-reasons small{display:block;color:var(--tx3);font-size:7px;text-transform:uppercase}.dna-pill b{display:block;font-size:9px;margin-top:2px;line-height:1.2}.dna-reasons{display:grid;grid-template-columns:1fr 1fr;gap:5px;margin-top:6px}.dna-reasons>div{padding:7px;border-radius:7px;background:linear-gradient(135deg,rgba(34,197,94,.08),rgba(59,130,246,.05));border:1px solid var(--bd)}.dna-reasons b{display:block;font-size:9px;line-height:1.25;margin-top:2px}.dna-lotbar{display:flex;gap:5px;margin-top:7px}.dna-lotbar span{flex:1;padding:7px;border-radius:7px;text-align:center;background:linear-gradient(90deg,rgba(34,197,94,.15),rgba(59,130,246,.12));font-size:8px;color:var(--tx2)}.dna-lotbar b{display:block;color:var(--tx);font-size:11px}.dna-footer{padding:10px;border-top:1px solid var(--bd);font-size:9px;color:var(--tx3)}@media(max-width:700px){.dna-grid{grid-template-columns:1fr}.dna-pills{grid-template-columns:1fr 1fr}.dna-reasons{grid-template-columns:1fr}.dna-card{padding:9px}}';document.head.appendChild(st);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,280);});else setTimeout(init,280);
})();