/* IPO Terminal Research Lens: evidence-first IPO research, not a recommendation engine. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function coverage(i){return ['price','size','lot','open','close','listing','sub','sub_qib','sub_nii','sub_retail','gmp','fresh','ofs','pe','roe','roce','rev','pat','ebitda','de','growth','prom'].filter(function(k){return ok(i[k]);}).length;}
function lens(i){var score=50,why=[],watch=[];var g=n(i.growth),roe=n(i.roe),roce=n(i.roce),de=n(i.de),pe=n(i.pe),sub=n(i.sub),gp=n(i.gmp_pct),ofs=n(i.ofs);if(g!=null){score+=g>=20?14:g>=12?9:g>=5?4:-5;if(g>=12)why.push('growth');}if(roe!=null&&roce!=null){score+=(roe>=15&&roce>=15)?14:(roe>=10&&roce>=10?6:-5);if(roe>=15&&roce>=15)why.push('return ratios');}if(de!=null){score+=de<=.3?8:de<=.6?4:de<=1?0:-8;if(de>1)watch.push('high debt');}if(pe!=null){score+=pe<=15?8:pe<=25?5:pe<=35?1:pe<=50?-4:-8;if(pe>35)watch.push('high P/E signal');}if(ofs!=null&&ofs>50)watch.push('high OFS mix');if(sub!=null){score+=sub>=50?8:sub>=20?6:sub>=10?4:sub>=3?2:sub<1?-4:0;if(sub>=10)why.push('strong demand');}if(gp!=null){score+=gp>=20?8:gp>=10?5:gp>=0?2:-5;if(gp>=10)why.push('positive GMP sentiment');if(gp<0)watch.push('negative GMP sentiment');}if(!ok(i.pe))watch.push('peer valuation unavailable');if(!ok(i.gmp))watch.push('GMP unavailable');var conf=Math.min(100,45+coverage(i)*2+(ok(i.source)?5:0)+(ok(i.gmp_source)?5:0));return {score:Math.max(0,Math.min(100,Math.round(score))),confidence:conf,why:why,risk:watch};}
function card(i){var a=lens(i),cl=a.score>=75?'gn':a.score>=60?'yl':'rd';return '<div class="news-item" style="border-left-color:var(--'+cl+')"><div style="display:flex;justify-content:space-between"><div><b style="font-size:14px">'+e(i.name)+'</b><div class="tx3" style="font-size:9px">'+e(i.type||'IPO')+' · '+e(i.sector||'Sector unavailable')+'</div></div><div><b class="'+cl+'" style="font-size:22px">'+a.score+'</b><span class="tx3" style="font-size:8px"> /100</span></div></div><div style="margin-top:5px"><span class="badge fut">Research signal</span> <span class="badge fut">Confidence '+a.confidence+'%</span></div><div style="font-size:11px;margin-top:7px"><b>Why it stands out:</b> '+e(a.why.length?a.why.join(' · '):'No strong positive signal in the currently available fields')+'</div><div class="tx3" style="font-size:10px;margin-top:4px"><b>What needs checking:</b> '+e(a.risk.length?a.risk.join(' · '):'No major warning detected from available fields')+'</div><div class="tx3" style="font-size:8px;margin-top:6px">Evidence coverage: '+coverage(i)+' key fields · GMP source: '+e(i.gmp_source||'none')+'</div></div>';}
function render(){var p=document.getElementById('ipo-research-lens'),c=document.getElementById('research-lens-content');if(!p||!c||!Array.isArray(window.ALL_IPOS))return;var list=ALL_IPOS.filter(function(i){return i&&i.name;}).map(function(i){return {i:i,s:lens(i)};}).sort(function(a,b){return b.s.score-a.s.score;}).slice(0,12);var h='<div class="panel-title">IPO Research Lens <button class="close-x" id="research-lens-close">Close</button></div><div style="padding:10px;border-bottom:1px solid var(--bd)"><b>Why does this IPO stand out?</b><div class="tx3" style="font-size:10px;margin-top:3px">Evidence-weighted research signals from the current data. It explains strengths and missing checks; it does not replace your investment decision.</div></div><div class="news-list">';list.forEach(function(x){h+=card(x.i);});h+='</div><div class="news-item" style="border-left-color:var(--pp)"><b style="color:var(--pp)">Evidence Memory</b><div class="tx3" style="font-size:10px;margin-top:4px">This lens is designed to learn from attributed research notes, video/podcast transcripts and your own checklist. Official company facts remain higher priority than educational opinions.</div></div>';c.innerHTML=h;p.classList.add('show');document.getElementById('research-lens-close').onclick=function(){p.classList.remove('show');};}
function init(){if(document.getElementById('b-research-lens'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='b-research-lens';b.textContent='Research Lens';b.onclick=render;box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-research-lens';var c=document.createElement('div');c.id='research-lens-content';p.appendChild(c);document.body.appendChild(p);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,180);});else setTimeout(init,180);
})();
