/* IPO Terminal Radar: evidence map. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function signal(i){var d={business:50,valuation:50,demand:50,gmp:50,structure:50},why=[],conf=0,g=n(i.growth),roe=n(i.roe),roce=n(i.roce),pe=n(i.pe),de=n(i.de),sub=n(i.sub),gp=n(i.gmp_pct),fresh=n(i.fresh),ofs=n(i.ofs);if(g!=null){d.business=g>=20?90:g>=12?78:g>=5?62:38;conf++;if(g>=12)why.push('growth');}if(roe!=null||roce!=null){var r=Math.max(roe||0,roce||0);d.business=Math.round((d.business+r*1.5)/2);conf++;if(r>=15)why.push('return ratios');}if(pe!=null){d.valuation=pe<=20?82:pe<=35?62:pe<=50?38:22;conf++;if(pe>35)why.push('rich P/E');}if(sub!=null){d.demand=sub>=50?95:sub>=20?82:sub>=10?70:sub>=3?58:sub<1?25:45;conf++;if(sub>=10)why.push('strong subscription');}if(gp!=null){d.gmp=gp>=20?90:gp>=10?75:gp>=0?60:25;conf++;if(gp>=10)why.push('positive GMP');}if(de!=null){d.structure=de<=.3?85:de<=.6?70:de<=1?55:30;conf++;if(de>1)why.push('high debt');}if(ofs!=null){d.structure=Math.max(0,d.structure-(ofs>80?30:ofs>50?15:0));conf++;}if(fresh!=null)conf++;var score=Math.round((d.business+d.valuation+d.demand+d.gmp+d.structure)/5),conflict=[];if(d.demand>=75&&d.valuation<=45)conflict.push('Demand strong but valuation stretched');if(d.gmp>=75&&d.business<=45)conflict.push('GMP is ahead of business evidence');if(d.business>=75&&d.structure<=45)conflict.push('Business strong but structure needs checking');if(d.demand<=35&&d.gmp>=75)conflict.push('GMP and subscription disagree');return {score:score,signals:d,confidence:Math.min(100,35+conf*7),why:why,conflict:conflict};}
function bar(label,val,cls){return '<div class="radar-row"><span>'+label+'</span><div class="radar-track"><i class="'+cls+'" style="width:'+val+'%"></i></div><b>'+Math.round(val)+'</b></div>';}
function render(){var p=document.getElementById('ipo-radar-panel');if(!p||!Array.isArray(window.ALL_IPOS))return;var list=window.ALL_IPOS.filter(function(i){return i&&i.name;}).map(function(i){return {i:i,s:signal(i)};}).sort(function(a,b){return b.s.score-a.s.score;}).slice(0,16),h='<div class="panel-title">IPO Radar <button class="close-x" id="radar-close">Close</button></div><div class="radar-intro"><b>See the IPO, not just the hype.</b><div class="tx3">Five evidence lanes: Business · Valuation · Demand · GMP · Structure. Missing data lowers confidence.</div></div><div class="radar-grid">'+list.map(function(x){var s=x.s,cl=s.score>=75?'gn':s.score>=55?'yl':'rd';return '<div class="radar-card"><div class="radar-head"><div><b>'+e(x.i.name)+'</b><span class="badge '+(x.i.type==='SME'?'sme':'mb')+'">'+e(x.i.type||'IPO')+'</span></div><div class="radar-score '+cl+'">'+s.score+'</div></div>'+bar('Business',s.signals.business,'r-business')+bar('Valuation',s.signals.valuation,'r-valuation')+bar('Demand',s.signals.demand,'r-demand')+bar('GMP',s.signals.gmp,'r-gmp')+bar('Structure',s.signals.structure,'r-structure')+'<div class="radar-meta">Confidence '+s.confidence+'%</div><div class="radar-why"><b>Why:</b> '+e(s.why.length?s.why.join(' · '):'Not enough evidence yet')+'</div>'+(s.conflict.length?'<div class="radar-conflict"><b>Conflict:</b> '+e(s.conflict.join(' · '))+'</div>':'')+'</div>';}).join('')+'</div>';p.innerHTML=h;p.classList.add('show');var b=document.getElementById('radar-btn');if(b)b.classList.add('active');document.getElementById('radar-close').onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};}
function init(){if(document.getElementById('radar-btn'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='radar-btn';b.textContent='IPO Radar';b.onclick=render;box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-radar-panel';document.body.appendChild(p);var st=document.createElement('style');st.textContent='.radar-intro{padding:10px;border-bottom:1px solid var(--bd)}.radar-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:8px;padding:8px}.radar-card{background:var(--card2);border:1px solid var(--bd);border-radius:10px;padding:10px}.radar-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.radar-head .badge{margin-left:5px}.radar-score{font-size:24px;font-weight:900}.radar-row{display:grid;grid-template-columns:68px 1fr 25px;gap:6px;align-items:center;font-size:9px;margin:5px 0}.radar-track{height:7px;background:var(--bd);border-radius:4px;overflow:hidden}.radar-track i{display:block;height:100%;border-radius:4px}.r-business{background:var(--gn)}.r-valuation{background:var(--bl)}.r-demand{background:var(--or)}.r-gmp{background:var(--pp)}.r-structure{background:var(--yl)}.radar-meta{font-size:8px;color:var(--tx3);margin-top:7px}.radar-why{font-size:9px;margin-top:7px}.radar-conflict{font-size:9px;margin-top:7px;padding:6px;border-left:3px solid var(--rd);background:rgba(239,68,68,.08)}@media(max-width:700px){.radar-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,220);});else setTimeout(init,220);
})();
