/* IPO Terminal IPO DNA: explain the shape of an IPO from available evidence. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function dna(i){var g=n(i.growth),roe=n(i.roe),roce=n(i.roce),de=n(i.de),pe=n(i.pe),fresh=n(i.fresh),ofs=n(i.ofs),prom=n(i.prom),sub=n(i.sub),gp=n(i.gmp_pct);return {growth:g!=null?(g>=25?'High growth':g>=12?'Growing':'Slow/negative'):'Unknown',profit:roe!=null&&roce!=null?(roe>=15&&roce>=15?'Strong returns':roe>=10&&roce>=10?'Moderate returns':'Weak returns'):'Unknown',valuation:pe!=null?(pe<=20?'Lower valuation':pe<=35?'Mid valuation':'High valuation'):'Unknown',balance:de!=null?(de<=.3?'Low debt':de<=.6?'Moderate debt':'High debt'):'Unknown',structure:fresh!=null?(fresh>=70?'Growth capital':fresh<30?'OFS-heavy':'Mixed issue'):'Unknown',promoter:prom!=null?(prom>=50?'High promoter holding':prom>=30?'Moderate promoter holding':'Low promoter holding'):'Unknown',demand:sub!=null?(sub>=10?'Strong demand':sub>=1?'Positive demand':'Weak/early demand'):'Unknown',sentiment:gp!=null?(gp>=20?'Strong GMP sentiment':gp>=5?'Positive GMP sentiment':gp<0?'Negative GMP sentiment':'Neutral GMP sentiment'):'Unknown'};}
function render(){var p=document.getElementById('ipo-dna-panel');if(!p||!Array.isArray(window.ALL_IPOS))return;var list=window.ALL_IPOS.filter(function(i){return i&&i.name;});var h='<div class="panel-title">IPO DNA <button class="close-x" id="dna-close">Close</button></div><div class="dna-intro"><b>IPO DNA = the structure behind the IPO.</b><div class="tx3">It summarizes business growth, profitability, valuation, balance sheet, issue structure, promoter alignment, demand and market sentiment. Unknown means the source has not supplied enough evidence yet.</div></div><div class="dna-grid">';list.forEach(function(i){var d=dna(i);h+='<div class="dna-card"><div class="dna-head"><b>'+e(i.name)+'</b><span class="badge '+(i.type==='SME'?'sme':'mb')+'">'+e(i.type||'IPO')+'</span></div><div class="dna-tags">'+Object.keys(d).map(function(k){return '<span class="dna-tag"><small>'+e(k)+'</small><b>'+e(d[k])+'</b></span>';}).join('')+'</div></div>';});h+='</div>';p.innerHTML=h;p.classList.add('show');var b=document.getElementById('dna-btn');if(b)b.classList.add('active');document.getElementById('dna-close').onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};}
function init(){if(document.getElementById('dna-btn'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='dna-btn';b.textContent='IPO DNA';b.onclick=function(){var p=document.getElementById('ipo-dna-panel');if(p&&p.classList.contains('show')){p.classList.remove('show');b.classList.remove('active');}else render();};box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-dna-panel';document.body.appendChild(p);var st=document.createElement('style');st.textContent='.dna-intro{padding:10px;border-bottom:1px solid var(--bd);font-size:11px}.dna-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:8px;padding:8px}.dna-card{background:var(--card2);border:1px solid var(--bd);border-radius:10px;padding:10px}.dna-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:7px}.dna-tags{display:grid;grid-template-columns:1fr 1fr;gap:5px}.dna-tag{padding:6px;border:1px solid var(--bd);border-radius:7px;background:var(--card)}.dna-tag small{display:block;color:var(--tx3);font-size:7px;text-transform:uppercase}.dna-tag b{display:block;font-size:9px;margin-top:2px}@media(max-width:700px){.dna-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,280);});else setTimeout(init,280);
})();
