/* IPO Terminal IPO DNA v2: richer evidence fingerprint. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function upperPrice(v){var m=String(v||'').replace(/,/g,'').match(/(\d+(?:\.\d+)?)\s*(?:-|–|—)\s*(\d+(?:\.\d+)?)/);return m?parseFloat(m[2]):n(v);}
function gmp(i){var g=n(i.gmp),p=upperPrice(i.price);if(g==null||p==null||g>p*2)return null;return g;}
function dna(i){var growth=n(i.growth),roe=n(i.roe),roce=n(i.roce),de=n(i.de),pe=n(i.pe),fresh=n(i.fresh),ofs=n(i.ofs),prom=n(i.prom),sub=n(i.sub),gp=n(i.gmp_pct),cash=n(i.operating_cf),pat=n(i.pat),ebitda=n(i.ebitda),g=gmp(i),out=[];
out.push(['Growth',growth!=null?(growth>=25?'High growth':growth>=12?'Growing':growth>=0?'Low growth':'Declining'):'Unknown']);
out.push(['Profitability',roe!=null&&roce!=null?(roe>=15&&roce>=15?'Strong returns':roe>=10&&roce>=10?'Moderate returns':'Weak returns'):'Partial / unknown']);
out.push(['Valuation',pe!=null?(pe<=20?'Lower valuation':pe<=35?'Mid valuation':'High valuation'):'Unknown']);
out.push(['Balance',de!=null?(de<=.3?'Low debt':de<=.6?'Moderate debt':'High debt'):'Unknown']);
out.push(['Issue structure',fresh!=null?(fresh>=70?'Growth capital':ofs!=null&&ofs>=50?'OFS-heavy':'Mixed issue'):'Unknown']);
out.push(['Promoter alignment',prom!=null?(prom>=50?'High holding':prom>=30?'Moderate holding':'Low holding'):'Unknown']);
out.push(['Demand',sub!=null?(sub>=10?'Strong demand':sub>=1?'Positive demand':'Weak / early demand'):'Unknown']);
out.push(['Market sentiment',g!=null&&gp!=null?(gp>=20?'Strong GMP sentiment':gp>=5?'Positive GMP sentiment':gp<0?'Negative GMP sentiment':'Neutral GMP sentiment'):'Not scored']);
out.push(['Cash quality',ok(cash)&&pat!=null?(n(cash)>=pat?'Cash supports profit':'Cash below profit'):'Unknown']);
out.push(['Earnings quality',pat!=null&&ebitda!=null?(n(ebitda)>=n(pat)?'EBITDA supports PAT':'Review margins'):'Unknown']);
out.push(['Use of proceeds',ok(i.use_of_proceeds)?'Purpose disclosed':'Unknown']);
var coverage=['growth','roe','roce','pe','de','fresh','ofs','prom','sub','gmp','rev','pat','ebitda','use_of_proceeds'].filter(function(k){return ok(i[k]);}).length;return {out:out,coverage:coverage,confidence:Math.min(100,Math.round(45+coverage*4)),gmpValid:g!=null};}
function render(){var p=document.getElementById('ipo-dna-panel');if(!p||!Array.isArray(window.ALL_IPOS))return;var list=window.ALL_IPOS.filter(function(i){return i&&i.name;});var h='<div class="panel-title">IPO DNA <button class="close-x" id="dna-close">Close</button></div><div class="dna-intro"><b>IPO DNA = the fingerprint behind the IPO.</b><div class="tx3">A deeper evidence map across growth, returns, valuation, leverage, issue structure, promoter alignment, demand, sentiment, cash quality and evidence coverage.</div></div><div class="dna-grid">';list.forEach(function(i){var d=dna(i),strong=d.out.filter(function(x){return /High|Strong|Lower|Low debt|Growth capital|Positive demand/.test(x[1]);}).length,weak=d.out.filter(function(x){return /Unknown|Weak|High valuation|High debt|OFS-heavy|Declining|Not scored|below/.test(x[1]);}).length;h+='<div class="dna-card"><div class="dna-head"><div><b>'+e(i.name)+'</b><div class="dna-sub">'+e(i.sector||'Sector unavailable')+' · '+e(i.type||'IPO')+'</div></div><span class="badge '+(i.type==='SME'?'sme':'mb')+'">'+e(i.type||'IPO')+'</span></div><div class="dna-score-row"><span>DNA confidence</span><b class="'+(d.confidence>=75?'gn':d.confidence>=60?'yl':'rd')+'">'+d.confidence+'%</b></div><div class="dna-tags">'+d.out.map(function(x){return '<span class="dna-tag"><small>'+e(x[0])+'</small><b>'+e(x[1])+'</b></span>';}).join('')+'</div><div class="dna-bottom"><span class="gn">'+strong+' positive lanes</span><span class="rd">'+weak+' review lanes</span><span class="tx3">'+d.coverage+' evidence fields</span></div>'+(i.gmp&&!d.gmpValid?'<div class="dna-warning">GMP value failed a price-consistency check and is excluded from DNA sentiment.</div>':'')+'</div>';});h+='</div>';p.innerHTML=h;p.classList.add('show');var b=document.getElementById('dna-btn');if(b)b.classList.add('active');document.getElementById('dna-close').onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};}
function init(){if(document.getElementById('dna-btn'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='dna-btn';b.textContent='IPO DNA';b.onclick=function(){var p=document.getElementById('ipo-dna-panel');if(p&&p.classList.contains('show')){p.classList.remove('show');b.classList.remove('active');}else render();};box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-dna-panel';document.body.appendChild(p);var st=document.createElement('style');st.textContent='.dna-intro{padding:10px;border-bottom:1px solid var(--bd);font-size:11px}.dna-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:9px;padding:9px}.dna-card{background:var(--card2);border:1px solid var(--bd);border-radius:12px;padding:11px}.dna-head{display:flex;justify-content:space-between;gap:8px;margin-bottom:7px}.dna-sub{font-size:9px;color:var(--tx3);margin-top:2px}.dna-score-row{display:flex;justify-content:space-between;padding:6px 8px;border-radius:8px;background:rgba(34,197,94,.07);margin-bottom:7px;font-size:9px}.dna-tags{display:grid;grid-template-columns:1fr 1fr;gap:5px}.dna-tag{padding:7px;border:1px solid var(--bd);border-radius:8px;background:var(--card)}.dna-tag small{display:block;color:var(--tx3);font-size:7px;text-transform:uppercase}.dna-tag b{display:block;font-size:9px;margin-top:2px}.dna-bottom{display:flex;flex-wrap:wrap;gap:8px;margin-top:8px;font-size:8px}.dna-warning{margin-top:8px;padding:7px;border-left:3px solid var(--yl);background:rgba(234,179,8,.08);font-size:8px;color:var(--tx2)}@media(max-width:700px){.dna-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,280);});else setTimeout(init,280);
})();
