/* IPO Terminal Research Lens: evidence-first analysis. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function lens(i){var score=50,why=[],risk=[],g=n(i.growth),roe=n(i.roe),roce=n(i.roce),de=n(i.de),pe=n(i.pe),sub=n(i.sub),gp=n(i.gmp_pct),ofs=n(i.ofs);if(g!=null){score+=g>=20?14:g>=12?9:g>=5?4:-5;if(g>=12)why.push('growth');}if(roe!=null&&roce!=null){score+=(roe>=15&&roce>=15)?14:(roe>=10&&roce>=10?6:-5);if(roe>=15&&roce>=15)why.push('return ratios');}if(de!=null){score+=de<=.3?8:de<=.6?4:de<=1?0:-8;if(de>1)risk.push('high debt');}if(pe!=null){score+=pe<=15?8:pe<=25?5:pe<=35?1:pe<=50?-4:-8;if(pe>35)risk.push('high P/E');}if(ofs!=null&&ofs>50)risk.push('high OFS mix');if(sub!=null){score+=sub>=50?8:sub>=20?6:sub>=10?4:sub>=3?2:sub<1?-4:0;if(sub>=10)why.push('strong demand');}if(gp!=null){score+=gp>=20?8:gp>=10?5:gp>=0?2:-5;if(gp>=10)why.push('positive GMP');if(gp<0)risk.push('negative GMP');}if(!ok(i.pe))risk.push('peer valuation unavailable');if(!ok(i.gmp))risk.push('GMP unavailable');var coverage=['price','size','lot','open','close','sub','gmp','fresh','ofs','pe','roe','roce','rev','pat','ebitda','de','growth','prom'].filter(function(k){return ok(i[k]);}).length;return {score:Math.max(0,Math.min(100,Math.round(score))),confidence:Math.min(100,45+coverage*3),why:why,risk:risk,coverage:coverage};}
function render(){var p=document.getElementById('ipo-research-lens'),c=document.getElementById('research-lens-content');if(!p||!c||!Array.isArray(window.ALL_IPOS))return;var list=window.ALL_IPOS.filter(function(i){return i&&i.name;}).map(function(i){return {i:i,s:lens(i)};}).sort(function(a,b){return b.s.score-a.s.score;}).slice(0,12),h='<div class="panel-title">IPO Research Lens <button class="close-x" id="research-lens-close">Close</button></div><div style="padding:10px;border-bottom:1px solid var(--bd)"><b>Evidence-weighted research signals</b><div class="tx3" style="font-size:10px;margin-top:3px">Explains strengths, risks and missing checks. It is not a personal investment recommendation.</div></div><div class="news-list">';list.forEach(function(x){var a=x.s,cl=a.score>=75?'gn':a.score>=60?'yl':'rd';h+='<div class="news-item" style="border-left-color:var(--'+cl+')"><div style="display:flex;justify-content:space-between"><div><b style="font-size:14px">'+e(x.i.name)+'</b><div class="tx3" style="font-size:9px">'+e(x.i.type||'IPO')+' · '+e(x.i.sector||'Sector unavailable')+'</div></div><div><b class="'+cl+'" style="font-size:22px">'+a.score+'</b><span class="tx3" style="font-size:8px"> /100</span></div></div><div style="font-size:10px;margin-top:6px"><b>Positive evidence:</b> '+e(a.why.length?a.why.join(' · '):'No strong positive signal yet')+'</div><div class="tx3" style="font-size:10px;margin-top:4px"><b>Check next:</b> '+e(a.risk.length?a.risk.join(' · '):'No major warning in available fields')+'</div><div class="tx3" style="font-size:8px;margin-top:6px">Evidence coverage: '+a.coverage+' fields · GMP source: '+e(x.i.gmp_source||'none')+'</div></div>';});h+='</div>';c.innerHTML=h;p.classList.add('show');var b=document.getElementById('b-research-lens');if(b)b.classList.add('active');document.getElementById('research-lens-close').onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};}
function init(){if(document.getElementById('b-research-lens'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='b-research-lens';b.textContent='Research Lens';b.onclick=render;box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-research-lens';var c=document.createElement('div');c.id='research-lens-content';p.appendChild(c);document.body.appendChild(p);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,180);});else setTimeout(init,180);
})();
