/* IPO Terminal Radar v3: colorful evidence map + application sizing. */
(function(){
'use strict';
function e(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[x];});}
function n(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function ok(v){return v!=null&&v!==''&&v!=='—'&&v!=='-';}
function validGmp(i){var gp=n(i.gmp_pct),g=n(i.gmp);return gp!=null&&gp>=-50&&gp<=100&&g!=null&&g>=-100&&g<=1000;}
function lot(i,m){var p=n(i.price),l=n(i.lot);return p!=null&&l!=null?p*l*m:null;}
function signal(i){var d={business:50,valuation:50,demand:50,gmp:50,structure:50},why=[],conf=0,g=n(i.growth),roe=n(i.roe),roce=n(i.roce),pe=n(i.pe),de=n(i.de),sub=n(i.sub),gp=validGmp(i)?n(i.gmp_pct):null,fresh=n(i.fresh),ofs=n(i.ofs);
 if(g!=null){d.business=g>=20?90:g>=12?78:g>=5?62:38;conf++;if(g>=12)why.push('growth');}
 if(roe!=null||roce!=null){var r=Math.max(roe||0,roce||0);d.business=Math.round((d.business+r*1.5)/2);conf++;if(r>=15)why.push('return ratios');}
 if(pe!=null&&pe>0&&pe<100){d.valuation=pe<=20?82:pe<=35?62:pe<=50?38:22;conf++;if(pe>35)why.push('rich P/E');}
 if(sub!=null){d.demand=sub>=50?95:sub>=20?82:sub>=10?70:sub>=3?58:sub<1?25:45;conf++;if(sub>=10)why.push('strong subscription');}
 if(gp!=null){d.gmp=gp>=20?90:gp>=10?75:gp>=5?68:gp>=0?60:25;conf++;if(gp>=10)why.push('positive GMP');}
 if(de!=null){d.structure=de<=.3?85:de<=.6?70:de<=1?55:30;conf++;if(de>1)why.push('high debt');}
 if(ofs!=null){d.structure=Math.max(0,d.structure-(ofs>80?30:ofs>50?15:0));conf++;}if(fresh!=null)conf++;
 var score=Math.round((d.business+d.valuation+d.demand+d.gmp+d.structure)/5),conflict=[];if(d.demand>=75&&d.valuation<=45)conflict.push('Demand strong but valuation stretched');if(d.gmp>=75&&d.business<=45)conflict.push('GMP is ahead of business evidence');if(d.business>=75&&d.structure<=45)conflict.push('Business strong but structure needs checking');if(d.demand<=35&&d.gmp>=75)conflict.push('GMP and subscription disagree');if(!validGmp(i)&&ok(i.gmp))conflict.push('GMP looks abnormal and is excluded');return {score:score,signals:d,confidence:Math.min(100,35+conf*7),why:why,conflict:conflict,gmpValid:gp!=null};}
function bar(label,val,cls){return '<div class="radar-row"><span>'+label+'</span><div class="radar-track"><i class="'+cls+'" style="width:'+val+'%"></i></div><b>'+Math.round(val)+'</b></div>';}
function render(){var p=document.getElementById('ipo-radar-panel');if(!p||!Array.isArray(window.ALL_IPOS))return;var list=window.ALL_IPOS.filter(function(i){return i&&i.name;}).map(function(i){return {i:i,s:signal(i)};}).sort(function(a,b){return b.s.score-a.s.score;}).slice(0,16),h='<div class="panel-title">IPO Radar <button class="close-x" id="radar-close">Close</button></div><div class="radar-intro"><div class="radar-hero"><span class="radar-icon">RADAR</span><div><b>See the IPO, not just the hype.</b><div class="tx3">Five evidence lanes: Business · Valuation · Demand · GMP · Structure.</div></div></div><div class="radar-note"><b>Application view:</b> every card shows the amount needed for <b>1 lot</b> and <b>2 lots</b> at the upper price. GMP is unofficial and abnormal values are excluded.</div></div><div class="radar-grid">'+list.map(function(x,idx){var s=x.s,i=x.i,cl=s.score>=75?'gn':s.score>=55?'yl':'rd',one=lot(i,1),two=lot(i,2),gmp=s.gmpValid?(ok(i.gmp_pct)?i.gmp_pct:'Positive'):('Ignored / unavailable');return '<div class="radar-card '+cl+'-radar"><div class="radar-head"><div><span class="radar-rank">#'+(idx+1)+'</span> <b>'+e(i.name)+'</b><span class="badge '+(i.type==='SME'?'sme':'mb')+'">'+e(i.type||'IPO')+'</span><div class="tx3">'+e(i.sector||'Sector unavailable')+' · '+e(i.status||'status TBA')+'</div></div><div class="radar-score '+cl+'">'+s.score+'</div></div>'+bar('Business',s.signals.business,'r-business')+bar('Valuation',s.signals.valuation,'r-valuation')+bar('Demand',s.signals.demand,'r-demand')+bar('GMP',s.signals.gmp,'r-gmp')+bar('Structure',s.signals.structure,'r-structure')+'<div class="radar-facts"><span>Price <b>'+e(i.price||'TBA')+'</b></span><span>Lot <b>'+e(i.lot||'TBA')+'</b></span><span>Growth <b>'+e(i.growth||'—')+'</b></span><span>D/E <b>'+e(i.de||'—')+'</b></span></div><div class="radar-apply"><div><small>1 LOT</small><b>'+(one!=null?'₹'+Math.round(one).toLocaleString('en-IN'):'TBA')+'</b></div><div><small>2 LOTS</small><b>'+(two!=null?'₹'+Math.round(two).toLocaleString('en-IN'):'TBA')+'</b></div></div><div class="radar-meta">Confidence '+s.confidence+'% · GMP: '+e(gmp)+'</div><div class="radar-why"><b>Why:</b> '+e(s.why.length?s.why.join(' · '):'Not enough evidence yet')+'</div>'+(s.conflict.length?'<div class="radar-conflict"><b>Check:</b> '+e(s.conflict.join(' · '))+'</div>':'')+'</div>';}).join('')+'</div>';p.innerHTML=h;p.classList.add('show');var b=document.getElementById('radar-btn');if(b)b.classList.add('active');document.getElementById('radar-close').onclick=function(){p.classList.remove('show');if(b)b.classList.remove('active');};}
function init(){if(document.getElementById('radar-btn'))return;var box=document.querySelector('.hbtns');if(!box)return;var b=document.createElement('button');b.className='hb';b.id='radar-btn';b.textContent='IPO Radar';b.onclick=function(){var p=document.getElementById('ipo-radar-panel');if(p&&p.classList.contains('show')){p.classList.remove('show');b.classList.remove('active');}else render();};box.appendChild(b);var p=document.createElement('div');p.className='panel';p.id='ipo-radar-panel';document.body.appendChild(p);var st=document.createElement('style');st.textContent='.radar-intro{padding:10px;border-bottom:1px solid var(--bd)}.radar-hero{display:flex;align-items:center;gap:9px;font-size:12px}.radar-icon{padding:9px 7px;border-radius:10px;background:linear-gradient(135deg,var(--or),var(--pp));color:#fff;font-size:8px;font-weight:900}.radar-note{margin-top:8px;padding:8px;border-radius:9px;background:linear-gradient(90deg,rgba(249,115,22,.10),rgba(168,85,247,.10),rgba(59,130,246,.08));font-size:9px}.radar-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:9px;padding:9px}.radar-card{background:var(--card2);border:1px solid var(--bd);border-radius:12px;padding:10px;box-shadow:0 2px 12px rgba(0,0,0,.12)}.radar-card.gn-radar{border-left:4px solid var(--gn)}.radar-card.yl-radar{border-left:4px solid var(--yl)}.radar-card.rd-radar{border-left:4px solid var(--rd)}.radar-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px;margin-bottom:8px}.radar-head .badge{margin-left:5px}.radar-rank{font-size:9px;color:var(--tx3)}.radar-score{font-size:25px;font-weight:900}.radar-row{display:grid;grid-template-columns:68px 1fr 25px;gap:6px;align-items:center;font-size:9px;margin:5px 0}.radar-track{height:7px;background:var(--bd);border-radius:4px;overflow:hidden}.radar-track i{display:block;height:100%;border-radius:4px}.r-business{background:var(--gn)}.r-valuation{background:var(--bl)}.r-demand{background:var(--or)}.r-gmp{background:var(--pp)}.r-structure{background:var(--yl)}.radar-facts{display:grid;grid-template-columns:1fr 1fr;gap:4px;margin-top:7px}.radar-facts span{padding:5px 6px;border-radius:6px;background:var(--card);font-size:8px;color:var(--tx3)}.radar-facts b{display:block;color:var(--tx);font-size:9px;margin-top:2px}.radar-apply{display:flex;gap:5px;margin-top:7px}.radar-apply>div{flex:1;text-align:center;padding:7px;border-radius:8px;background:linear-gradient(90deg,rgba(34,197,94,.15),rgba(59,130,246,.12));border:1px solid var(--bd)}.radar-apply small{display:block;font-size:7px;color:var(--tx3)}.radar-apply b{display:block;font-size:12px;margin-top:2px}.radar-meta{font-size:8px;color:var(--tx3);margin-top:7px}.radar-why{font-size:9px;margin-top:7px}.radar-conflict{font-size:9px;margin-top:7px;padding:6px;border-left:3px solid var(--rd);background:rgba(239,68,68,.08)}@media(max-width:700px){.radar-grid{grid-template-columns:1fr}.radar-card{padding:9px}}';document.head.appendChild(st);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(init,220);});else setTimeout(init,220);
})();