/* IPO Terminal upgrade layer: GMP, SME, search, allotment, subscriptions, anchors, broker UPI copy and data timestamp. */
(function(){
'use strict';
var GMP_URL='data/gmp.json',SUB_URL='data/subscriptions.json',SME_URL='data/sme-ipos.json',IPO_URL='data/ipo-data.json';
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(x){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x];});}
function arr(v){if(Array.isArray(v))return v;if(v&&Array.isArray(v.data))return v.data;if(v&&Array.isArray(v.records))return v.records;return [];}
function first(o,keys){for(var i=0;i<keys.length;i++)if(o&&o[keys[i]]!=null&&o[keys[i]]!=='')return o[keys[i]];return null;}
function num(v){var m=String(v==null?'':v).replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?parseFloat(m[0]):null;}
function injectStyle(){if(document.getElementById('ipo-upgrade-style'))return;var s=document.createElement('style');s.id='ipo-upgrade-style';s.textContent=''
+'.ipo-upgrade-search{position:sticky;top:8px;z-index:9000;margin:8px 0;padding:9px 11px;border:1px solid rgba(255,255,255,.18);border-radius:14px;background:rgba(20,27,43,.58);box-shadow:0 10px 28px rgba(0,0,0,.18),inset 0 1px 0 rgba(255,255,255,.12);backdrop-filter:blur(18px) saturate(145%);-webkit-backdrop-filter:blur(18px) saturate(145%)}'
+'.ipo-upgrade-search input{width:100%;border:1px solid rgba(255,255,255,.16);outline:0;border-radius:10px;padding:9px 12px;background:rgba(255,255,255,.07);color:var(--tx);font-size:12px}'
+'.ipo-upgrade-search input::placeholder{color:var(--tx3)}'
+'.upgrade-panel-note{padding:10px;color:var(--tx3);font-size:10px}'
+'.upgrade-scroll{overflow-x:auto}.upgrade-scroll table{min-width:720px}'
+'.upgrade-footer{position:fixed;left:0;right:0;bottom:0;z-index:10000;padding:7px 12px;text-align:center;font-size:9px;line-height:1.3;color:var(--tx2);background:rgba(8,12,20,.78);border-top:1px solid rgba(255,255,255,.14);backdrop-filter:blur(16px) saturate(140%);-webkit-backdrop-filter:blur(16px) saturate(140%)}'
+'body{padding-bottom:44px!important}'
+'.upgrade-copy{margin-left:5px;border:1px solid var(--bd);background:rgba(255,255,255,.06);color:var(--tx2);border-radius:6px;padding:2px 6px;font-size:8px;cursor:pointer}'
+'.upgrade-copy.copied{color:var(--gn);border-color:var(--gn)}'
+'.upgrade-positive{color:var(--gn)!important;font-weight:800}.upgrade-negative{color:var(--rd)!important;font-weight:800}'
+'.upgrade-anchor{font-size:9px;color:var(--tx2);line-height:1.4}'
+'@media(max-width:900px){.ipo-upgrade-search{top:4px}.upgrade-footer{font-size:8px;padding:6px 8px}.upgrade-panel-note{font-size:9px}.ipo-upgrade-search{margin:6px 0}}';document.head.appendChild(s);}
function addSeo(){var head=document.head;function meta(name,content,prop){var sel=prop?'meta[property="'+name+'"]':'meta[name="'+name+'"]',m=head.querySelector(sel);if(!m){m=document.createElement('meta');if(prop)m.setAttribute('property',name);else m.setAttribute('name',name);head.appendChild(m);}m.setAttribute('content',content);}var title=document.querySelector('title');if(title)title.textContent='IPO Terminal — Live IPO Calendar, GMP & Fundamentals';meta('description','IPO Terminal with IPO calendar, fundamentals, GMP, subscription data, SME IPOs, allotment links, filings and IPO research tools.','');meta('theme-color','#0a0e17','');meta('og:title','IPO Terminal — Live IPO Calendar, GMP & Fundamentals',true);meta('og:description','Track Indian IPOs, GMP, subscription, SME IPOs, filings and fundamentals in one terminal.',true);meta('og:type','website',true);meta('og:url','https://devrajai.github.io/ipo-terminal/',true);var vp=head.querySelector('meta[name="viewport"]');if(!vp){vp=document.createElement('meta');vp.name='viewport';head.appendChild(vp);}vp.content='width=device-width,initial-scale=1.0,maximum-scale=5.0';}
function addFooter(){if(document.getElementById('ipo-upgrade-footer'))return;var f=document.createElement('footer');f.id='ipo-upgrade-footer';f.className='upgrade-footer';f.textContent='Disclaimer: This site is for informational purposes only. Data may not be accurate or real-time. GMP is unofficial and unregulated. Not SEBI registered. Not investment advice. Verify independently.';document.body.appendChild(f);}
function addSearch(){if(document.getElementById('ipo-global-search'))return;var hdr=document.querySelector('.hdr');if(!hdr)return;var box=document.createElement('div');box.className='ipo-upgrade-search';box.id='ipo-global-search';box.innerHTML='<input id="ipo-search" type="search" autocomplete="off" placeholder="Search IPO / company name…">';hdr.insertAdjacentElement('afterend',box);var input=box.querySelector('input');input.addEventListener('input',function(){var q=input.value.trim().toLowerCase();document.querySelectorAll('.ipo-table tbody tr').forEach(function(r){r.style.display=!q||r.textContent.toLowerCase().indexOf(q)>=0?'':'none';});});}
function addNav(id,label){var nav=document.querySelector('.hbtns');if(!nav||document.getElementById(id))return null;var b=document.createElement('button');b.className='hb';b.id=id;b.type='button';b.textContent=label;nav.appendChild(b);return b;}
function addPanel(id,title,buttonId){if(document.getElementById(id))return document.getElementById(id);var p=document.createElement('div');p.className='panel';p.id=id;p.innerHTML='<div class="panel-title">'+esc(title)+' <button class="close-x" type="button">Close</button></div><div class="upgrade-panel-note">Loading…</div>';document.body.appendChild(p);var close=p.querySelector('.close-x');close.onclick=function(){p.classList.remove('show');var b=document.getElementById(buttonId);if(b)b.classList.remove('active');};return p;}
function bindFeature(id,panelId,load){var b=document.getElementById(id),p=document.getElementById(panelId);if(!b||!p||b.dataset.upgradeBound)return;b.dataset.upgradeBound='1';b.onclick=function(){if(p.classList.contains('show')){p.classList.remove('show');b.classList.remove('active');return;}document.querySelectorAll('.panel.show').forEach(function(x){x.classList.remove('show');});document.querySelectorAll('.hbtns .hb.active').forEach(function(x){x.classList.remove('active');});b.classList.add('active');p.classList.add('show');load();setTimeout(function(){p.scrollIntoView({behavior:'smooth',block:'start'});},20);};}
function loadJson(url){return fetch(url+'?ts='+Date.now(),{cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json();});}
function renderGmp(p){var box=p.querySelector('.upgrade-panel-note');loadJson(GMP_URL).then(function(raw){var rows=arr(raw);if(!rows.length){box.textContent='GMP data updating...';return;}var h='<div class="upgrade-scroll"><table class="ipo-table"><thead><tr><th>IPO Name</th><th>Issue Price</th><th>GMP (₹)</th><th>Est. Listing</th><th>GMP %</th><th>Kostak (₹)</th><th>Updated</th></tr></thead><tbody>';rows.forEach(function(x){var price=first(x,['issue_price','price','issuePrice']),g=first(x,['gmp','GMP']),listing=first(x,['estimated_listing','est_listing','listing']),pct=first(x,['gmp_pct','gmp_percent','gmpPercent']);if(pct==null){var gn=num(g),pn=num(price);pct=gn!=null&&pn?((gn/pn)*100).toFixed(1)+'%':'—';}var cls=num(g)>=0?'upgrade-positive':'upgrade-negative';h+='<tr><td><b>'+esc(first(x,['name','ipo_name','company'])||'—')+'</b></td><td>'+esc(price||'—')+'</td><td class="'+cls+'">'+esc(g||'—')+'</td><td>'+esc(listing||'—')+'</td><td class="'+cls+'">'+esc(pct||'—')+'</td><td>'+esc(first(x,['kostak','kostak_rate'])||'—')+'</td><td>'+esc(first(x,['updated_at','updated','timestamp'])||raw.updated_at||'—')+'</td></tr>';});h+='</tbody></table></div>';box.innerHTML=h;}).catch(function(){box.textContent='GMP data updating...';});}
function renderSme(p){var box=p.querySelector('.upgrade-panel-note');loadJson(SME_URL).then(function(raw){var rows=arr(raw);if(!rows.length){box.textContent='SME IPO data updating...';return;}var h='<div class="upgrade-scroll"><table class="ipo-table"><thead><tr><th>Company</th><th>Exchange (BSE/NSE)</th><th>Open Date</th><th>Close Date</th><th>Issue Size</th><th>Status</th></tr></thead><tbody>';rows.forEach(function(x){h+='<tr><td><b>'+esc(first(x,['company','name','ipo_name'])||'—')+'</b></td><td>'+esc(first(x,['exchange','market'])||'—')+'</td><td>'+esc(first(x,['open_date','open'])||'—')+'</td><td>'+esc(first(x,['close_date','close'])||'—')+'</td><td>'+esc(first(x,['issue_size','size'])||'—')+'</td><td>'+esc(first(x,['status'])||'—')+'</td></tr>';});h+='</tbody></table></div>';box.innerHTML=h;}).catch(function(){box.textContent='SME IPO data updating...';});}
function renderAllotment(){var c=document.getElementById('allot-container');if(!c||c.dataset.upgraded)return;c.dataset.upgraded='1';c.innerHTML='<div style="padding:12px"><form id="ipo-allot-form"><label style="display:block;font-size:10px;color:var(--tx3);font-weight:700;margin-bottom:5px">PAN NUMBER</label><input id="ipo-pan" name="pan" inputmode="text" maxlength="10" autocomplete="off" placeholder="Enter PAN" style="width:100%;max-width:360px;padding:9px 10px;border:1px solid var(--bd);border-radius:8px;background:var(--card2);color:var(--tx);outline:0;text-transform:uppercase"><button type="submit" class="hb" style="margin:8px 0 6px">Check Allotment</button></form><div style="font-size:10px;color:var(--tx3);line-height:1.5">Allotment is checked directly on registrar sites. Your PAN is never stored.</div><div style="margin-top:7px;font-size:10px">NSDL: <a href="https://iepf.gov.in/IEPF/allotmentstatus.html" target="_blank" rel="noopener noreferrer" class="news-link">Check NSDL / IEPF allotment status</a></div></div>';document.getElementById('ipo-allot-form').onsubmit=function(e){e.preventDefault();var input=document.getElementById('ipo-pan');var v=(input.value||'').trim().toUpperCase();if(!/^[A-Z]{5}[0-9]{4}[A-Z]$/.test(v)){input.setCustomValidity('Enter a valid 10-character PAN.');input.reportValidity();return;}input.setCustomValidity('');window.open('https://web.cdslindia.com/myeasi/Home/Login','_blank','noopener,noreferrer');input.value='';};}
function loadSubs(){var map={};return loadJson(SUB_URL).then(function(raw){arr(raw).forEach(function(x){var n=String(first(x,['name','ipo_name','company'])||'').trim().toLowerCase();if(n)map[n]=x;});return map;}).catch(function(){return map;});}
function patchOpenTable(map){var c=document.getElementById('open-container');if(!c)return;var table=c.querySelector('table');if(!table)return;var head=table.querySelector('thead tr');if(!head||head.dataset.subUpgrade)return;head.dataset.subUpgrade='1';var old=[];head.querySelectorAll('th').forEach(function(th,i){old[i]=th.textContent.trim().toLowerCase();});var subIndex=-1;old.forEach(function(t,i){if(t.indexOf('subscription')>=0)subIndex=i;});if(subIndex>=0){var ths=head.querySelectorAll('th');var target=ths[subIndex];target.remove();}
['QIB','NII','RII','Total (x times)'].forEach(function(t){var th=document.createElement('th');th.textContent=t;head.appendChild(th);});
var rows=table.querySelectorAll('tbody tr');rows.forEach(function(r){var name=(r.cells[0]?r.cells[0].textContent:'').trim().toLowerCase(),x=map[name]||map[Object.keys(map).find(function(k){return k&&name.indexOf(k)>=0||k&&k.indexOf(name)>=0;})]||{};if(subIndex>=0&&r.cells[subIndex])r.cells[subIndex].remove();var vals=[first(x,['qib','QIB','qib_x','qib_times']),first(x,['nii','NII','hni','hni_x','nii_times']),first(x,['rii','RII','retail','retail_x','rii_times']),first(x,['total','Total','total_x','subscription'])];vals.forEach(function(v){var td=document.createElement('td');td.textContent=v==null||v===''?'—':v;r.appendChild(td);});});}
function observeSubscriptions(){var ready=false,map={};loadSubs().then(function(m){map=m;ready=true;patchOpenTable(map);});var c=document.getElementById('open-container');if(!c)return;var mo=new MutationObserver(function(){if(ready)patchOpenTable(map);});mo.observe(c,{childList:true,subtree:true});setTimeout(function(){mo.disconnect();},15000);}
function addAnchorFields(){var panel=document.getElementById('ipo-fundamentals-panel');if(!panel)return;var table=panel.querySelector('table');if(!table||table.dataset.anchorUpgrade)return;var list=window.ALL_IPOS||[];if(!list.length)return;table.dataset.anchorUpgrade='1';var h=table.querySelector('thead tr');var th=document.createElement('th');th.textContent='Anchor Investors';h.appendChild(th);table.querySelectorAll('tbody tr').forEach(function(r,i){var name=(r.cells[0]?r.cells[0].textContent:'').trim().toLowerCase();var x=list.find(function(v){var n=String(v.name||'').toLowerCase();return n===name||n&&name.indexOf(n)>=0||n.indexOf(name)>=0;})||list[i]||{};var td=document.createElement('td');td.className='upgrade-anchor';td.textContent=first(x,['anchor_investors','anchorInvestors','anchors'])||'—';r.appendChild(td);});}
function watchAnchors(){var mo=new MutationObserver(addAnchorFields);mo.observe(document.body,{childList:true,subtree:true});setTimeout(function(){mo.disconnect();},20000);}
function colorListed(){document.querySelectorAll('#list-container tr').forEach(function(r){if(r.dataset.glColor)return;var txt=r.textContent||'',m=txt.match(/[+-]\s*\d+(?:\.\d+)?\s*%/);if(!m)return;r.dataset.glColor='1';var n=num(m[0]);var cells=r.querySelectorAll('td');var target=cells[cells.length-1]||r;if(n>0)target.classList.add('upgrade-positive');if(n<0)target.classList.add('upgrade-negative');});}
function copyButtons(){document.querySelectorAll('.panel').forEach(function(p){var walker=document.createTreeWalker(p,NodeFilter.SHOW_TEXT),nodes=[],n;while(n=walker.nextNode())nodes.push(n);nodes.forEach(function(t){var val=(t.nodeValue||'').trim();if(!/@/.test(val)||val.length>80||t.parentElement.closest('button'))return;var m=val.match(/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+/);if(!m)return;var el=t.parentElement;if(el.dataset.upiCopy)return;var b=document.createElement('button');b.className='upgrade-copy';b.type='button';b.textContent='Copy';b.onclick=function(){navigator.clipboard.writeText(m[0]).then(function(){b.textContent='Copied';b.classList.add('copied');setTimeout(function(){b.textContent='Copy';b.classList.remove('copied');},1200);}).catch(function(){var ta=document.createElement('textarea');ta.value=m[0];document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();b.textContent='Copied';setTimeout(function(){b.textContent='Copy';},1200);});};el.appendChild(b);el.dataset.upiCopy='1';});});}
function observeDynamic(){var mo=new MutationObserver(function(){colorListed();copyButtons();addAnchorFields();});mo.observe(document.body,{childList:true,subtree:true});setTimeout(function(){mo.disconnect();},30000);}
function timestamp(){var host=document.querySelector('.hdr');if(!host||document.getElementById('ipo-last-updated'))return;var x=document.createElement('span');x.id='ipo-last-updated';x.style.cssText='margin-left:auto;font-size:8px;color:var(--tx3);font-weight:700;text-align:right';var row=host.querySelector('div[style*="align-items:center"]');(row||host).appendChild(x);loadJson(IPO_URL).then(function(d){x.textContent='Last updated: '+(d.updated_at||d.last_updated||'—');}).catch(function(){x.textContent='Last updated: unavailable';});}
function start(){injectStyle();addSeo();addFooter();addSearch();addNav('gmp-btn','Live GMP');addNav('sme-btn','SME IPOs');var gp=addPanel('ipo-gmp-panel','Live GMP','gmp-btn'),sp=addPanel('ipo-sme-panel','SME IPOs','sme-btn');bindFeature('gmp-btn','ipo-gmp-panel',function(){renderGmp(gp);});bindFeature('sme-btn','ipo-sme-panel',function(){renderSme(sp);});renderAllotment();observeSubscriptions();watchAnchors();observeDynamic();timestamp();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(start,1200);});else setTimeout(start,1200);
})();
